# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `date` gem.
# Please instead update this file by running `bin/tapioca gem date`.

class Date
  include ::Comparable
  include ::DateAndTime::Zones
  include ::DateAndTime::Calculations

  def infinite?; end
end

Date::DATE_FORMATS = T.let(T.unsafe(nil), Hash)

class Date::Infinity < ::Numeric
  def initialize(d = T.unsafe(nil)); end

  def +@; end
  def -@; end
  def <=>(other); end
  def abs; end
  def coerce(other); end
  def finite?; end
  def infinite?; end
  def nan?; end
  def to_f; end
  def zero?; end

  protected

  def d; end
end

Date::NOT_SET = T.let(T.unsafe(nil), Object)
Date::VERSION = T.let(T.unsafe(nil), String)
