# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/syntax_tree/all/syntax_tree.rbi
#
# syntax_tree-5.3.0

module SyntaxTree
end
class SyntaxTree::Formatter < PrettierPrint
end
class SyntaxTree::Formatter::SemanticVersion < Gem::Version
end
class SyntaxTree::Formatter::Options
end
class SyntaxTree::Location
end
class SyntaxTree::Node
end
module SyntaxTree::ArrayMatch
end
class SyntaxTree::BEGINBlock < SyntaxTree::Node
end
class SyntaxTree::CHAR < SyntaxTree::Node
end
class SyntaxTree::ENDBlock < SyntaxTree::Node
end
class SyntaxTree::EndContent < SyntaxTree::Node
end
class SyntaxTree::AliasNode < SyntaxTree::Node
end
class SyntaxTree::AliasNode::AliasArgumentFormatter
end
class SyntaxTree::ARef < SyntaxTree::Node
end
class SyntaxTree::ARefField < SyntaxTree::Node
end
class SyntaxTree::ArgParen < SyntaxTree::Node
end
class SyntaxTree::Args < SyntaxTree::Node
end
class SyntaxTree::ArgBlock < SyntaxTree::Node
end
class SyntaxTree::ArgStar < SyntaxTree::Node
end
class SyntaxTree::ArgsForward < SyntaxTree::Node
end
class SyntaxTree::ArrayLiteral < SyntaxTree::Node
end
class SyntaxTree::ArrayLiteral::BreakableSpaceSeparator
end
class SyntaxTree::ArrayLiteral::QWordsFormatter
end
class SyntaxTree::ArrayLiteral::QSymbolsFormatter
end
class SyntaxTree::ArrayLiteral::EmptyWithCommentsFormatter
end
class SyntaxTree::AryPtn < SyntaxTree::Node
end
class SyntaxTree::AryPtn::RestFormatter
end
module SyntaxTree::AssignFormatting
end
class SyntaxTree::Assign < SyntaxTree::Node
end
class SyntaxTree::Assoc < SyntaxTree::Node
end
class SyntaxTree::AssocSplat < SyntaxTree::Node
end
class SyntaxTree::Backref < SyntaxTree::Node
end
class SyntaxTree::Backtick < SyntaxTree::Node
end
module SyntaxTree::HashKeyFormatter
end
class SyntaxTree::HashKeyFormatter::Labels
end
class SyntaxTree::HashKeyFormatter::Rockets
end
class SyntaxTree::BareAssocHash < SyntaxTree::Node
end
class SyntaxTree::Begin < SyntaxTree::Node
end
class SyntaxTree::PinnedBegin < SyntaxTree::Node
end
class SyntaxTree::Binary < SyntaxTree::Node
end
class SyntaxTree::BlockVar < SyntaxTree::Node
end
class SyntaxTree::BlockVar::Separator
end
class SyntaxTree::BlockArg < SyntaxTree::Node
end
class SyntaxTree::BodyStmt < SyntaxTree::Node
end
class SyntaxTree::FlowControlFormatter
end
class SyntaxTree::Break < SyntaxTree::Node
end
class SyntaxTree::CallOperatorFormatter
end
class SyntaxTree::CallChainFormatter
end
class SyntaxTree::CallNode < SyntaxTree::Node
end
class SyntaxTree::Case < SyntaxTree::Node
end
class SyntaxTree::RAssign < SyntaxTree::Node
end
class SyntaxTree::ClassDeclaration < SyntaxTree::Node
end
class SyntaxTree::Comma < SyntaxTree::Node
end
class SyntaxTree::Command < SyntaxTree::Node
end
class SyntaxTree::CommandCall < SyntaxTree::Node
end
class SyntaxTree::Comment < SyntaxTree::Node
end
class SyntaxTree::Const < SyntaxTree::Node
end
class SyntaxTree::ConstPathField < SyntaxTree::Node
end
class SyntaxTree::ConstPathRef < SyntaxTree::Node
end
class SyntaxTree::ConstRef < SyntaxTree::Node
end
class SyntaxTree::CVar < SyntaxTree::Node
end
class SyntaxTree::DefNode < SyntaxTree::Node
end
class SyntaxTree::Defined < SyntaxTree::Node
end
class SyntaxTree::BlockNode < SyntaxTree::Node
end
class SyntaxTree::BlockNode::BlockOpenFormatter
end
class SyntaxTree::RangeNode < SyntaxTree::Node
end
module SyntaxTree::Quotes
end
class SyntaxTree::DynaSymbol < SyntaxTree::Node
end
class SyntaxTree::Else < SyntaxTree::Node
end
class SyntaxTree::Elsif < SyntaxTree::Node
end
class SyntaxTree::EmbDoc < SyntaxTree::Node
end
class SyntaxTree::EmbExprBeg < SyntaxTree::Node
end
class SyntaxTree::EmbExprEnd < SyntaxTree::Node
end
class SyntaxTree::EmbVar < SyntaxTree::Node
end
class SyntaxTree::Ensure < SyntaxTree::Node
end
class SyntaxTree::ExcessedComma < SyntaxTree::Node
end
class SyntaxTree::Field < SyntaxTree::Node
end
class SyntaxTree::FloatLiteral < SyntaxTree::Node
end
class SyntaxTree::FndPtn < SyntaxTree::Node
end
class SyntaxTree::For < SyntaxTree::Node
end
class SyntaxTree::GVar < SyntaxTree::Node
end
class SyntaxTree::HashLiteral < SyntaxTree::Node
end
class SyntaxTree::HashLiteral::EmptyWithCommentsFormatter
end
class SyntaxTree::Heredoc < SyntaxTree::Node
end
class SyntaxTree::HeredocBeg < SyntaxTree::Node
end
class SyntaxTree::HeredocEnd < SyntaxTree::Node
end
class SyntaxTree::HshPtn < SyntaxTree::Node
end
class SyntaxTree::HshPtn::KeywordFormatter
end
class SyntaxTree::HshPtn::KeywordRestFormatter
end
class SyntaxTree::Ident < SyntaxTree::Node
end
module SyntaxTree::ContainsAssignment
end
module SyntaxTree::Ternaryable
end
class SyntaxTree::ConditionalFormatter
end
class SyntaxTree::IfNode < SyntaxTree::Node
end
class SyntaxTree::IfOp < SyntaxTree::Node
end
class SyntaxTree::Imaginary < SyntaxTree::Node
end
class SyntaxTree::In < SyntaxTree::Node
end
class SyntaxTree::Int < SyntaxTree::Node
end
class SyntaxTree::IVar < SyntaxTree::Node
end
class SyntaxTree::Kw < SyntaxTree::Node
end
class SyntaxTree::KwRestParam < SyntaxTree::Node
end
class SyntaxTree::Label < SyntaxTree::Node
end
class SyntaxTree::LabelEnd < SyntaxTree::Node
end
class SyntaxTree::Lambda < SyntaxTree::Node
end
class SyntaxTree::LambdaVar < SyntaxTree::Node
end
class SyntaxTree::LBrace < SyntaxTree::Node
end
class SyntaxTree::LBracket < SyntaxTree::Node
end
class SyntaxTree::LParen < SyntaxTree::Node
end
class SyntaxTree::MAssign < SyntaxTree::Node
end
class SyntaxTree::MethodAddBlock < SyntaxTree::Node
end
class SyntaxTree::MLHS < SyntaxTree::Node
end
class SyntaxTree::MLHSParen < SyntaxTree::Node
end
class SyntaxTree::ModuleDeclaration < SyntaxTree::Node
end
class SyntaxTree::MRHS < SyntaxTree::Node
end
class SyntaxTree::Next < SyntaxTree::Node
end
class SyntaxTree::Op < SyntaxTree::Node
end
class SyntaxTree::OpAssign < SyntaxTree::Node
end
module SyntaxTree::Parentheses
end
class SyntaxTree::Params < SyntaxTree::Node
end
class SyntaxTree::Params::OptionalFormatter
end
class SyntaxTree::Params::KeywordFormatter
end
class SyntaxTree::Params::KeywordRestFormatter
end
class SyntaxTree::Paren < SyntaxTree::Node
end
class SyntaxTree::Period < SyntaxTree::Node
end
class SyntaxTree::Program < SyntaxTree::Node
end
class SyntaxTree::QSymbols < SyntaxTree::Node
end
class SyntaxTree::QSymbolsBeg < SyntaxTree::Node
end
class SyntaxTree::QWords < SyntaxTree::Node
end
class SyntaxTree::QWordsBeg < SyntaxTree::Node
end
class SyntaxTree::RationalLiteral < SyntaxTree::Node
end
class SyntaxTree::RBrace < SyntaxTree::Node
end
class SyntaxTree::RBracket < SyntaxTree::Node
end
class SyntaxTree::Redo < SyntaxTree::Node
end
class SyntaxTree::RegexpContent < SyntaxTree::Node
end
class SyntaxTree::RegexpBeg < SyntaxTree::Node
end
class SyntaxTree::RegexpEnd < SyntaxTree::Node
end
class SyntaxTree::RegexpLiteral < SyntaxTree::Node
end
class SyntaxTree::RescueEx < SyntaxTree::Node
end
class SyntaxTree::Rescue < SyntaxTree::Node
end
class SyntaxTree::RescueMod < SyntaxTree::Node
end
class SyntaxTree::RestParam < SyntaxTree::Node
end
class SyntaxTree::Retry < SyntaxTree::Node
end
class SyntaxTree::ReturnNode < SyntaxTree::Node
end
class SyntaxTree::RParen < SyntaxTree::Node
end
class SyntaxTree::SClass < SyntaxTree::Node
end
class SyntaxTree::Statements < SyntaxTree::Node
end
class SyntaxTree::StringContent < SyntaxTree::Node
end
class SyntaxTree::StringConcat < SyntaxTree::Node
end
class SyntaxTree::StringDVar < SyntaxTree::Node
end
class SyntaxTree::StringEmbExpr < SyntaxTree::Node
end
class SyntaxTree::StringLiteral < SyntaxTree::Node
end
class SyntaxTree::Super < SyntaxTree::Node
end
class SyntaxTree::SymBeg < SyntaxTree::Node
end
class SyntaxTree::SymbolContent < SyntaxTree::Node
end
class SyntaxTree::SymbolLiteral < SyntaxTree::Node
end
class SyntaxTree::Symbols < SyntaxTree::Node
end
class SyntaxTree::SymbolsBeg < SyntaxTree::Node
end
class SyntaxTree::TLambda < SyntaxTree::Node
end
class SyntaxTree::TLamBeg < SyntaxTree::Node
end
class SyntaxTree::TopConstField < SyntaxTree::Node
end
class SyntaxTree::TopConstRef < SyntaxTree::Node
end
class SyntaxTree::TStringBeg < SyntaxTree::Node
end
class SyntaxTree::TStringContent < SyntaxTree::Node
end
class SyntaxTree::TStringEnd < SyntaxTree::Node
end
class SyntaxTree::Not < SyntaxTree::Node
end
class SyntaxTree::Unary < SyntaxTree::Node
end
class SyntaxTree::Undef < SyntaxTree::Node
end
class SyntaxTree::Undef::UndefArgumentFormatter
end
class SyntaxTree::UnlessNode < SyntaxTree::Node
end
class SyntaxTree::LoopFormatter
end
class SyntaxTree::UntilNode < SyntaxTree::Node
end
class SyntaxTree::VarField < SyntaxTree::Node
end
class SyntaxTree::VarRef < SyntaxTree::Node
end
class SyntaxTree::PinnedVarRef < SyntaxTree::Node
end
class SyntaxTree::VCall < SyntaxTree::Node
end
class SyntaxTree::VoidStmt < SyntaxTree::Node
end
class SyntaxTree::When < SyntaxTree::Node
end
class SyntaxTree::When::Separator
end
class SyntaxTree::WhileNode < SyntaxTree::Node
end
class SyntaxTree::Word < SyntaxTree::Node
end
class SyntaxTree::Words < SyntaxTree::Node
end
class SyntaxTree::WordsBeg < SyntaxTree::Node
end
class SyntaxTree::XString < SyntaxTree::Node
end
class SyntaxTree::XStringLiteral < SyntaxTree::Node
end
class SyntaxTree::YieldNode < SyntaxTree::Node
end
class SyntaxTree::ZSuper < SyntaxTree::Node
end
module SyntaxTree::DSL
end
class SyntaxTree::BasicVisitor
end
class SyntaxTree::BasicVisitor::VisitMethodError < StandardError
end
class SyntaxTree::BasicVisitor::VisitMethodChecker
end
class SyntaxTree::Visitor < SyntaxTree::BasicVisitor
end
class SyntaxTree::Visitor::FieldVisitor < SyntaxTree::BasicVisitor
end
class SyntaxTree::Visitor::JSONVisitor < SyntaxTree::Visitor::FieldVisitor
end
class SyntaxTree::Visitor::MatchVisitor < SyntaxTree::Visitor::FieldVisitor
end
class SyntaxTree::Visitor::MutationVisitor < SyntaxTree::BasicVisitor
end
class SyntaxTree::Visitor::PrettyPrintVisitor < SyntaxTree::Visitor::FieldVisitor
end
class SyntaxTree::Environment
end
class SyntaxTree::Environment::Local
end
module SyntaxTree::WithEnvironment
end
class SyntaxTree::Parser < Ripper
end
class SyntaxTree::Parser::ParseError < StandardError
end
class SyntaxTree::Parser::SingleByteString
end
class SyntaxTree::Parser::MultiByteString
end
class SyntaxTree::Parser::TokenList
end
class SyntaxTree::Parser::PinVisitor < SyntaxTree::Visitor
end
class SyntaxTree::Pattern
end
class SyntaxTree::Pattern::CompilationError < StandardError
end
class SyntaxTree::Search
end
module SyntaxTree::Index
end
class SyntaxTree::Index::Location
end
class SyntaxTree::Index::ClassDefinition
end
class SyntaxTree::Index::ModuleDefinition
end
class SyntaxTree::Index::MethodDefinition
end
class SyntaxTree::Index::SingletonMethodDefinition
end
class SyntaxTree::Index::FileComments
end
class SyntaxTree::Index::FileComments::Parser < Ripper
end
class SyntaxTree::Index::FileComments::FileSource
end
class SyntaxTree::Index::FileComments::StringSource
end
class SyntaxTree::Index::EntryComments
  include Enumerable
end
class SyntaxTree::Index::ISeqBackend
end
class SyntaxTree::Index::ParserBackend
end
class SyntaxTree::Index::ParserBackend::IndexVisitor < SyntaxTree::Visitor
end
module SyntaxTree::YARV
end
class SyntaxTree::YARV::Bf
end
class SyntaxTree::YARV::Compiler < SyntaxTree::BasicVisitor
end
class SyntaxTree::YARV::Compiler::Options
end
class SyntaxTree::YARV::Compiler::RubyVisitor < SyntaxTree::BasicVisitor
end
class SyntaxTree::YARV::Compiler::RubyVisitor::CompilationError < StandardError
end
class SyntaxTree::YARV::Decompiler
  include SyntaxTree::DSL
end
class SyntaxTree::YARV::Decompiler::BlockLabel
  include SyntaxTree::DSL
end
class SyntaxTree::YARV::Disassembler
end
class SyntaxTree::YARV::InstructionSequence
end
class SyntaxTree::YARV::InstructionSequence::InstructionList
  include Enumerable
end
class SyntaxTree::YARV::InstructionSequence::InstructionList::Node
end
class SyntaxTree::YARV::InstructionSequence::Stack
end
class SyntaxTree::YARV::InstructionSequence::Label
end
class SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchBreak < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchEnsure < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchNext < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchRedo < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchRescue < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::InstructionSequence::CatchRetry < SyntaxTree::YARV::InstructionSequence::CatchEntry
end
class SyntaxTree::YARV::CallData
end
class SyntaxTree::YARV::AdjustStack
end
class SyntaxTree::YARV::AnyToString
end
class SyntaxTree::YARV::BranchIf
end
class SyntaxTree::YARV::BranchNil
end
class SyntaxTree::YARV::BranchUnless
end
class SyntaxTree::YARV::CheckKeyword
end
class SyntaxTree::YARV::CheckMatch
end
class SyntaxTree::YARV::CheckType
end
class SyntaxTree::YARV::ConcatArray
end
class SyntaxTree::YARV::ConcatStrings
end
class SyntaxTree::YARV::DefineClass
end
class SyntaxTree::YARV::Defined
end
class SyntaxTree::YARV::DefineMethod
end
class SyntaxTree::YARV::DefineSMethod
end
class SyntaxTree::YARV::Dup
end
class SyntaxTree::YARV::DupArray
end
class SyntaxTree::YARV::DupHash
end
class SyntaxTree::YARV::DupN
end
class SyntaxTree::YARV::ExpandArray
end
class SyntaxTree::YARV::GetBlockParam
end
class SyntaxTree::YARV::GetBlockParamProxy
end
class SyntaxTree::YARV::GetClassVariable
end
class SyntaxTree::YARV::GetConstant
end
class SyntaxTree::YARV::GetGlobal
end
class SyntaxTree::YARV::GetInstanceVariable
end
class SyntaxTree::YARV::GetLocal
end
class SyntaxTree::YARV::GetLocalWC0
end
class SyntaxTree::YARV::GetLocalWC1
end
class SyntaxTree::YARV::GetSpecial
end
class SyntaxTree::YARV::Intern
end
class SyntaxTree::YARV::InvokeBlock
end
class SyntaxTree::YARV::InvokeSuper
end
class SyntaxTree::YARV::Jump
end
class SyntaxTree::YARV::Leave
end
class SyntaxTree::YARV::NewArray
end
class SyntaxTree::YARV::NewArrayKwSplat
end
class SyntaxTree::YARV::NewHash
end
class SyntaxTree::YARV::NewRange
end
class SyntaxTree::YARV::Nop
end
class SyntaxTree::YARV::ObjToString
end
class SyntaxTree::YARV::Once
end
class SyntaxTree::YARV::OptAnd
end
class SyntaxTree::YARV::OptAref
end
class SyntaxTree::YARV::OptArefWith
end
class SyntaxTree::YARV::OptAset
end
class SyntaxTree::YARV::OptAsetWith
end
class SyntaxTree::YARV::OptCaseDispatch
end
class SyntaxTree::YARV::OptDiv
end
class SyntaxTree::YARV::OptEmptyP
end
class SyntaxTree::YARV::OptEq
end
class SyntaxTree::YARV::OptGE
end
class SyntaxTree::YARV::OptGetConstantPath
end
class SyntaxTree::YARV::OptGT
end
class SyntaxTree::YARV::OptLE
end
class SyntaxTree::YARV::OptLength
end
class SyntaxTree::YARV::OptLT
end
class SyntaxTree::YARV::OptLTLT
end
class SyntaxTree::YARV::OptMinus
end
class SyntaxTree::YARV::OptMod
end
class SyntaxTree::YARV::OptMult
end
class SyntaxTree::YARV::OptNEq
end
class SyntaxTree::YARV::OptNewArrayMax
end
class SyntaxTree::YARV::OptNewArrayMin
end
class SyntaxTree::YARV::OptNilP
end
class SyntaxTree::YARV::OptNot
end
class SyntaxTree::YARV::OptOr
end
class SyntaxTree::YARV::OptPlus
end
class SyntaxTree::YARV::OptRegExpMatch2
end
class SyntaxTree::YARV::OptSendWithoutBlock
end
class SyntaxTree::YARV::OptSize
end
class SyntaxTree::YARV::OptStrFreeze
end
class SyntaxTree::YARV::OptStrUMinus
end
class SyntaxTree::YARV::OptSucc
end
class SyntaxTree::YARV::Pop
end
class SyntaxTree::YARV::PutNil
end
class SyntaxTree::YARV::PutObject
end
class SyntaxTree::YARV::PutObjectInt2Fix0
end
class SyntaxTree::YARV::PutObjectInt2Fix1
end
class SyntaxTree::YARV::PutSelf
end
class SyntaxTree::YARV::PutSpecialObject
end
class SyntaxTree::YARV::PutString
end
class SyntaxTree::YARV::Send
end
class SyntaxTree::YARV::SetBlockParam
end
class SyntaxTree::YARV::SetClassVariable
end
class SyntaxTree::YARV::SetConstant
end
class SyntaxTree::YARV::SetGlobal
end
class SyntaxTree::YARV::SetInstanceVariable
end
class SyntaxTree::YARV::SetLocal
end
class SyntaxTree::YARV::SetLocalWC0
end
class SyntaxTree::YARV::SetLocalWC1
end
class SyntaxTree::YARV::SetN
end
class SyntaxTree::YARV::SetSpecial
end
class SyntaxTree::YARV::SplatArray
end
class SyntaxTree::YARV::Swap
end
class SyntaxTree::YARV::Throw
end
class SyntaxTree::YARV::TopN
end
class SyntaxTree::YARV::ToRegExp
end
module SyntaxTree::YARV::Legacy
end
class SyntaxTree::YARV::Legacy::GetClassVariable
end
class SyntaxTree::YARV::Legacy::OptGetInlineCache
end
class SyntaxTree::YARV::Legacy::OptSetInlineCache
end
class SyntaxTree::YARV::Legacy::SetClassVariable
end
class SyntaxTree::YARV::LocalTable
end
class SyntaxTree::YARV::LocalTable::BlockLocal
end
class SyntaxTree::YARV::LocalTable::PlainLocal
end
class SyntaxTree::YARV::LocalTable::Lookup
end
class SyntaxTree::YARV::Assembler
end
class SyntaxTree::YARV::Assembler::ObjectVisitor < SyntaxTree::YARV::Compiler::RubyVisitor
end
class SyntaxTree::YARV::VM
  extend Forwardable
end
class SyntaxTree::YARV::VM::Jump
end
class SyntaxTree::YARV::VM::Leave
end
class SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::TopFrame < SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::BlockFrame < SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::MethodFrame < SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::ClassFrame < SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::RescueFrame < SyntaxTree::YARV::VM::Frame
end
class SyntaxTree::YARV::VM::ThrownError < StandardError
end
class SyntaxTree::YARV::VM::ReturnError < SyntaxTree::YARV::VM::ThrownError
end
class SyntaxTree::YARV::VM::BreakError < SyntaxTree::YARV::VM::ThrownError
end
class SyntaxTree::YARV::VM::NextError < SyntaxTree::YARV::VM::ThrownError
end
class SyntaxTree::YARV::VM::FrozenCore
end
class SyntaxTree::YARV::VM::NullEvents
end
class SyntaxTree::YARV::VM::STDOUTEvents
end
class SyntaxTree::YARV::VM::Stack
end
